services:
  web:
    build: .
    expose:
      - 3000
    volumes:
      - sqlite:/app/db
    environment:
      - VIRTUAL_HOST=lokiframe.local
      - VIRTUAL_PORT=3000
      - DB_PATH=db
      - PORT=3000

volumes:
  sqlite:
networks:
  default:
    external:
      name: local
